env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    github_token: "ENCRYPTED[!429719b9a000c43260dab8e3393e52f6542ce4ad32c456c6b7956827acd56e841200d8cd235f13a5225439d3a4053b57!]"
    bot_api: "ENCRYPTED[!52ac7e69475567cc5d6021b27ff40b57f56360a221db9acc864f3bb540f05d07aeade14f7a8b43314898fe1abcef787e!]"
    chat_id: "ENCRYPTED[!dbfe16d7f5e4dc086c9bec0f62b45fa01462ce8057ed667799b29e2c2f423c06fec9e964f72f9fb27f893287c08b3ffb!]"

# store information about git here
    gmail: ismailduyan80@gmail.com
    
# User Version ( dont touch )
    user_version: 2 # lets start from 1

task:
    name: havoc
    timeout_in: 260m
    container:
      dockerfile: Dockerfile
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - curl -o /tmp/ci/function https://raw.githubusercontent.com/Headache01/cirrus-script/main/function
      - curl -o /tmp/ci/download_ccache https://raw.githubusercontent.com/Headache01/cirrus-script/main/download_ccache
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - curl -o build https://raw.githubusercontent.com/Headache01/cirrus-script/main/build
      - bash build
    upload_ccache_script: # Upload ccache to cloud foreground
      - curl -o upload_ccache https://raw.githubusercontent.com/Headache01/cirrus-script/main/upload_ccache
      - bash upload_ccache # Ccache uploading script


