env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    github_token: "ENCRYPTED[!4f8fa2072eea8b85980e2a76661ba125c4bf3c0862fc413e0edf6d2d47ef8af904b7df5074b6157491ea8fa6ca3d047d!]"
    bot_api: "ENCRYPTED[!b2ababea0cdc609e231658441c71276b7844485be06359abef6bc61e7cdd8d350bdf901ec018595839c15dae0300f5f6!]"
    chat_id: "ENCRYPTED[!1a95e2193b6afb65c3d40845e8e2582fcddc4e7e975b7b82224326d6a188aad39bb1723f8a553edec97e4493a28e1203!]"

# store information about git here
    gmail: ismailduyan80@gmail.com
    
# User Version ( dont touch )
    user_version: 2 # lets start from 1

task:
    name: havoc
    timeout_in: 260m
    container:
      dockerfile: Dockerfile
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - curl -o /tmp/ci/function https://raw.githubusercontent.com/projects-nexus/cirrus-script/main/function
      - curl -o /tmp/ci/download_ccache https://raw.githubusercontent.com/projects-nexus/cirrus-script/main/download_ccache
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - curl -o build https://raw.githubusercontent.com/projects-nexus/cirrus-script/main/build
      - bash build
    upload_ccache_script: # Upload ccache to cloud foreground
      - curl -o upload_ccache https://raw.githubusercontent.com/projects-nexus/cirrus-script/main/upload_ccache
      - bash upload_ccache # Ccache uploading script
